Add a Dummy authentication driver
horde/Auth pull request #1
Opened 2017-10-22 11:59 UTC by ralflang

The Dummy authentication driver allows to password protect a horde installation with a fixed set of login credentials.
It is fast for a small amount of users as it keeps everything in memory and is easy to set up.
This makes it useful for stripped down installations like demo setups, API providers, no DB setups, integration tests etc.

Different from the Auto driver, it actually requires the user to login.

The driver provides actual functionality to add, remove or update users and keep changes, though it is pointless. Without actually changing the driver configuration, the driver will forget any changes with the next request. 

Out of scope of this individual PR:
Provide Core and base integration
Provide a callback mechanism and a sample callback to persist any changes.

2017-10-27 09:44 UTC, yunosh requested changes

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> +class Horde_Auth_Dummy extends Horde_Auth_Base
This is rather a Mock driver, it should be called like that.

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> + * It is meant to be used for throwaway setups, satellite systems or for
One empty line here to separate description from summery

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> + * Copyright 2017-2018 Horde LLC (http://www.horde.org/)
It's not 2018 yet ;-)

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> +               $credentials['password'],
Fix indention

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> +     * @throws Horde_Auth_Exception
Doesn't throw an exception. Some other methods don't either.

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> +        if ($this->exists($userId)) {
This is easier to follow by negating the check, i.e. `if (!$this->exists || $this->_compare) throw`

2017-10-27 09:44 UTC, yunosh commented on lib/Horde/Auth/Dummy.php
> +        return $encrypted == Horde_Auth::getCryptedPassword($plaintext,
Indentions. Wrap the first argument already, then line-up further arguments.

2017-10-27 09:44 UTC, yunosh commented on test/Horde/Auth/Unit/DummyCryptShowTest.php
> + * PHP version 5
Unnecessary line

2017-10-27 09:44 UTC, yunosh commented on test/Horde/Auth/Unit/DummyCryptShowTest.php
> +        $this->setExpectedException(Horde_Auth_Exception::class);
::class makes travis fail on php 5.4.

2017-10-27 09:45 UTC, yunosh commented
And please rebase on current master to fix the travis 5.6 and 7.0 builds

2017-10-29 08:43 UTC, ralflang commented
Closing this for new, clean https://github.com/horde/Auth/pull/2

2017-10-29 08:43 UTC, closed without merging